spring:
  application:
    name: spring-heterogeneous-database-sample

  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

mysql:
  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:13306/default
        username: root
        password: 12345
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:23306/default
        username: root
        password: 12345

oracle:
  datasource:
    hikari:
      master:
        driver-class-name: oracle.jdbc.OracleDriver
#        jdbc-url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
#        jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
#        jdbc-url: jdbc:oracle:thin:@localhost:1521/ORCLCDB
#        jdbc-url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
        jdbc-url: jdbc:oracle:thin:@localhost:1521/FREECDB
        username: system
        password: oracle123
      slave:
        driver-class-name: oracle.jdbc.OracleDriver
#        jdbc-url: jdbc:oracle:thin:@localhost:2521/ORCLPDB1
#        jdbc-url: jdbc:oracle:thin:@localhost:2521:ORCLCDB
#        jdbc-url: jdbc:oracle:thin:@localhost:2521/ORCLCDB
#        jdbc-url: jdbc:oracle:thin:@localhost:2521/ORCLPDB1
        jdbc-url: jdbc:oracle:thin:@localhost:2521/freepdb1
        username: system
        password: oracle123

# DB ?? ?? (????)
logging:
  level:
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.resource.transaction: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG            # ???? SQL ?? ??
    org.hibernate.type.descriptor.sql: TRACE # SQL ???? ??? ? ??

#spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true               # SQL? ?? ?? ??
#        use_sql_comments: true         # SQL? ?? ??
#        generate_statistics: true      # SQL ?? ?? ??
#        jdbc:
#          batch_size: 30               # ?? ?? ? SQL ?? ????
#  datasource:
#    hikari:
#      maximum-pool-size: 10            # HikariCP ??? ? ??
#      pool-name: HikariCP-MyApp
#
#logging:
#  level:
