version: '3.7'
# 볼륨제거
# docker-compose down --volumes --remove-orphans
services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    restart: always
    ports:
      - "13306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql_master/mysql:/var/lib/mysql
      - ./mysql_master/sql:/docker-entrypoint-initdb.d
      - ./mysql_master/my.cnf:/etc/mysql/my.cnf  # my.cnf 마운트 추가

  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    restart: always
    ports:
      - "23306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql_slave/mysql:/var/lib/mysql
      - ./mysql_slave/sql:/docker-entrypoint-initdb.d
      - ./mysql_slave/my.cnf:/etc/mysql/my.cnf  # my.cnf 마운트 추가

#  oracle19c_master:
#    image: gvenzl/oracle-free:latest
#    container_name: oracle19c_master
#    environment:
#      - ORACLE_PASSWORD=oracle123
#      - ORACLE_DATABASE=ORCLCDB
#      - ORACLE_PDB=ORCLPDB1
#      - ORACLE_CHARACTERSET=AL32UTF8
#    ports:
#      - "1521:1521"
#      - "5500:5500"
#    volumes:
#      - oracle_master_data:/opt/oracle/oradata
#    restart: always
#
#  oracle19c_slave:
#    image: gvenzl/oracle-free:latest
#    container_name: oracle19c_slave
#    environment:
#      - ORACLE_PASSWORD=oracle123
#      - ORACLE_DATABASE=ORCLCDB
#      - ORACLE_PDB=ORCLPDB1
#      - ORACLE_CHARACTERSET=AL32UTF8
#    ports:
#      - "2521:1521"
#      - "5501:5500" # 포트 변경
#    volumes:
#      - oracle_slave_data:/opt/oracle/oradata
#    restart: always
#
#volumes:
#  oracle_master_data:
#    driver: local
#  oracle_slave_data:
#    driver: local
